bootstrap-node:
  - enr:-LG4QIETd82w1eK9SdNonvQ7NKRMB6FAu1Vu18hAu1JLtvj4EhTQMEDrITrzGOMbLwma0P2nd8B5Nq8LqUA2lu5AsjGGAYOBWSQyh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhANYSimJc2VjcDI1NmsxoQPi8uDTLh_mSmhkS_btSM-B7alvzetdnEi2W8sVvtIVgIN1ZHCCD6A
  - enr:-LG4QBXLvZj3a7n1Pi8FUxHGRCMRSrIKJDs9zcpDt908kmdTeFnhPpYlv6eYLKkuZr1pmg1_wUyduH4SJAd7D-en7_6GAYOBWfSGh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhBKox3yJc2VjcDI1NmsxoQKessJNzFBjrgn2vlxK7MRaD3j_97nDZH34cMhKLAIj6IN1ZHCCD6A
  - enr:-LG4QMS6sRasvgCOCsgbYA3Ctk99RWavHzOyZJqAeJZYD_xiNB1A7ZUXR1HMDfzWZDYdq-gG4bZQWWl3U-pWSZULVUOGAYOBhigeh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCOALBnLxsAAP__________gmlkgnY0gmlwhDRKYZ2Jc2VjcDI1NmsxoQO0zloqB0LP_gd2_-HWyUnE9o0hF-TDozerdTio3rR7MYN1ZHCCD6A
peer:
  - enr:-MK4QKpWi2ymV9TJgLl5Zd4EFL86_XGuhD7lBPZAHbguE-tOW7_xJqdbb_2wxd5xxE7E6gE8tMJKpEwkKWmqlLegNuyGAYORrEbbh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBOtKTULxwCACQEAAAAAAAAgmlkgnY0gmlwhBKL9kuJc2VjcDI1NmsxoQJfagFSuQe4DOX0aq3so4Vw-YaoLY_nWFjzGaGpcppq_4hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
  - enr:-MK4QBZF87PY3Ggoi8v8_FNkY4Gl5WV7jBh4ChK7spG7YEUFDjGbHNLCTT3ORms6jixMoJ-EoSu7OKlotADrB85ax--GAYORs1Xfh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBegxb8LxsCAP__________gmlkgnY0gmlwhDbjznmJc2VjcDI1NmsxoQPgzLsasgR0X44Btr0SLYz81MdJyKsvfbulcfdWYuQdeYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
  - enr:-MK4QKjW_gexseRTP-6YjExgE__l60vHciINo8labiFNFiLTJmZ4bdWD6_Fd9rWslzA9MIri7bu7s_fDroiOD9rHadCGAYORtLr_h2F0dG5ldHOIAAAAAAAAAACEZXRoMpBegxb8LxsCAP__________gmlkgnY0gmlwhAMKPfeJc2VjcDI1NmsxoQKw3W2yV-eCZ5Li74XoiTeW_KJm9cClYzJp_HJ8hFSRDIhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
  - enr:-MK4QLm1LfF6Y9Er6_MrdMs4tsfcLcCgQdRPLLuZWPOXuWx3T8e-SHiIck2vNvCAsBxg7o0E8hPwf_wVRmYPIjnGY1eGAYORtfwTh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBegxb8LxsCAP__________gmlkgnY0gmlwhBKIqqqJc2VjcDI1NmsxoQJokytkBc8kA9PNECinwI62CUyOhRxfTBWeVI0YtFL3BIhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
contract-deployment-block: 26049
rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
datadir: /root/chain/cl/
execution-endpoint: /root/chain/el/geth.ipc

